const sideDrawingCoordinates = {
    'rgb(255, 0, 0)': [
        {
            imageType: 'pants',
            sourceX: 151,
            sourceY: 355,
            offsetX: 0,
            offsetY: 128,
            width: 64,
        },
        {
            imageType: 'shirt',
            sourceX: 151,
            sourceY: 355,
            offsetX: 0,
            offsetY: 0,
            width: 64,
        },
    ],
    'rgb(0, 255, 0)': [
        {
            imageType: 'pants',
            sourceX: 217,
            sourceY: 355,
            offsetX: 64,
            offsetY: 128,
            width: 64,
        },
        {
            imageType: 'pants',
            sourceX: 231,
            sourceY: 74,
            offsetX: 64,
            offsetY: 0,
            width: 128,
        },
        {
            imageType: 'pants',
            sourceX: 308,
            sourceY: 355,
            offsetX: 128,
            offsetY: 128,
            width: 64,
        },
        {
            imageType: 'shirt',
            sourceX: 217,
            sourceY: 355,
            offsetX: 0,
            offsetY: 0,
            width: 64,
        },

        {
            imageType: 'shirt',
            sourceX: 231,
            sourceY: 74,
            offsetX: 64,
            offsetY: 0,
            width: 128,
        },

        {
            imageType: 'shirt',
            sourceX: 308,
            sourceY: 355,
            offsetX: 192,
            offsetY: 0,
            width: 64,
        },
    ],
    'rgb(0, 0, 255)': [
        {
            imageType: 'pants',
            sourceX: 440,
            sourceY: 355,
            offsetX: 64,
            offsetY: 128,
            width: 64,
        },
        {
            imageType: 'pants',
            sourceX: 427,
            sourceY: 74,
            offsetX: 64,
            offsetY: 0,
            width: 128,
        },
        {
            imageType: 'pants',
            sourceX: 85,
            sourceY: 355,
            offsetX: 128,
            offsetY: 128,
            width: 64,
        },
        {
            imageType: 'shirt',
            sourceX: 440,
            sourceY: 355,
            offsetX: 0,
            offsetY: 0,
            width: 64,
        },
        {
            imageType: 'shirt',
            sourceX: 427,
            sourceY: 74,
            offsetX: 64,
            offsetY: 0,
            width: 128,
        },
        {
            imageType: 'shirt',
            sourceX: 85,
            sourceY: 355,
            offsetX: 192,
            offsetY: 0,
            width: 64,
        },
    ],
    'rgb(255, 255, 0)': [
        {
            imageType: 'pants',
            sourceX: 374,
            sourceY: 355,
            offsetX: 0,
            offsetY: 128,
            width: 64,
        },
        {
            imageType: 'shirt',
            sourceX: 374,
            sourceY: 355,
            offsetX: 0,
            offsetY: 0,
            width: 64,
        },
    ],
}

export default sideDrawingCoordinates
